### ISSUE TITLE
Translation from Transifex are not taken into account

### ISSUE THREAD

**Issue by Jerome-Herbinet** [theCalcaholic/nextcloud-secrets#33]
Hello,
I've checked your translations files, and I've noticed that at least some wordings remain in English despite there are French translations. You can for example check the secret share screen open by the recipient. Everything is in English, although my UI and my browser are in French.
Thanks by advance ! 😉

**Comment by theCalcaholic** [comment]
Should now be fixed in v1.5.1 (the translations themselves are still missing, though - should be available in a few weeks)

**Comment by theCalcaholic** [comment]
Translations are released with 1.5.2

**Comment by ThibautPlg** [comment]
Hi,
Sorry to reopen the issue, but the same thing is happening again. Since your release 2.1.1, a few strings were translated, including the ones from the "Reveal" screen, which contains important information and makes our non-english speakers a bit scared.
Do you think a new release including all the new transifex pushes could be made?

Best regards,
